name: Build and Release macOS-alias-utils

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build Binaries
        run: chmod +x build && ./build
        env:
          APP_VERSION: ${{ github.ref_name }}

      - name: Package ZIP
        run: |
          zip macOS-alias-utils.${{ github.ref_name }}.zip \
          bin/* \
          scripts/* \
          README.md \
          LICENSE

      - name: Publish Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: macOS-alias-utils.${{ github.ref_name }}.zip
          generate_release_notes: true
